const filtersSet = {
	react: {
		name: 'React',
		id: 'react',
		type: 'MULTISELECT',
		selected: false,
		query: 'React',
	},
	angular: {
		name: 'Angular',
		id: 'angular',
		type: 'MULTISELECT',
		selected: false,
		query: 'Angular',
	},
	vue: {
		name: 'Vue',
		id: 'vue',
		type: 'MULTISELECT',
		selected: false,
		query: 'Vue',
	},
	webComponents: {
		name: 'Web Components',
		id: 'webComponents',
		type: 'MULTISELECT',
		selected: false,
		query: 'Web Components',
	},
	graphQL: {
		name: 'GraphQL',
		id: 'graphQL',
		type: 'MULTISELECT',
		selected: false,
		query: 'GraphQL',
	},
	js: {
		name: 'JS',
		id: 'js',
		type: 'MULTISELECT',
		selected: false,
		query: 'JS',
	},
	css: {
		name: 'CSS',
		id: 'css',
		type: 'MULTISELECT',
		selected: false,
		query: 'CSS',
	},
	html5: {
		name: 'HTML 5',
		id: 'html5',
		type: 'MULTISELECT',
		selected: false,
		query: 'HTML 5',
	},
	websiteDesign: {
		name: 'Website Design',
		id: 'websiteDesign',
		type: 'MULTISELECT',
		selected: false,
		query: 'Website Design',
	},
	android: {
		name: 'Android',
		id: 'android',
		type: 'MULTISELECT',
		selected: false,
		query: 'Android',
	},
	ios: {
		name: 'IOS',
		id: 'ios',
		type: 'MULTISELECT',
		selected: false,
		query: 'IOS',
	},
};
export { filtersSet };
